config/routes.rb
Microblog::Application.routes.draw do
  root to: "paginas#index"
  match "/ajuda", to: "paginas#ajuda"
  match "/sobre", to: "paginas#sobre"

  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]

  match "/signup",  to: "usuarios#new"
  match "/login",   to: "sessions#new"
  match "/logout",  to: "sessions#destroy", via: :delete
  

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :nome, :email, :password, :password_confirmation

  validates :nome, presence: true, length: { maximum: 50 }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: VALID_EMAIL_REGEX, uniqueness: { case_sensitive: false }

  has_secure_password

  before_save :create_remember_token

  private
  
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  def index
  end

  def ajuda
  end

  def sobre
  end
end

app/controllers/sessions_controller.rb
# encoding: utf-8

class SessionsController < ApplicationController
  def new
  end

  def create
    usuario = Usuario.find_by_email(params[:session][:email])
    if usuario && usuario.authenticate(params[:session][:password])
      login usuario
      redirect_to usuario      
    else
      flash.now[:alert] = "Usuário/senha inválidos!"
      render 'new'      
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def show
    @usuario = Usuario.find(params[:id])
  end

  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.new(params[:usuario])
    if @usuario.save
      login @usuario
      redirect_to @usuario, notice: "Bem vindo ao site!"
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def titulo_completo(titulo)
    base = 'MicroBlog IT'
    if titulo.empty?
      base
    else 
      "#{base} | #{titulo}"
    end
  end
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(usuario)
    cookies.permanent[:remember_token] = usuario.remember_token
    @usuario_logado = usuario
  end

  def logout
    usuario_logado = nil
    cookies.delete(:remember_token)
  end

  def logado?
    usuario_logado.present?
  end

  def usuario_logado
    @usuario_logado ||= usuario_com_remember_token
  end

  def usuario_com_remember_token
    remember_token = cookies[:remember_token]
    Usuario.find_by_remember_token(remember_token) unless remember_token.nil?
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
  def gravatar_for(usuario)
    gravatar_id = Digest::MD5::hexdigest(usuario.email.downcase)
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png"
    image_tag(gravatar_url, alt: usuario.nome, class: "gravatar")
  end
end

app/views/layouts/_cabecalho.html.erb
<header>
  <%= image_tag("logo.png", alt: "MicroBlog IT", class: "round") %>
  <nav class="round">
    <ul>
      <li><%= link_to "Início", root_url %></li>
      <li><%= link_to "Sobre", sobre_url %></li>
      <% if logado? %>
        <li><%= link_to "Perfil", usuario_logado %></li>
        <li><%= link_to "Sair", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Entre no site", login_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_rodape.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Ajuda", ajuda_url %></li>
      <li><%= link_to "Contato", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', media: 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  media: 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag    "application", media: "all" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= titulo_completo(yield(:title)) %></title>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/cabecalho' %>
      <section class="round">
        <% if flash[:alert] %>
          <p class="alert"><%= flash[:alert] %></p>
        <% end %>
        <% if flash[:notice] %>
          <p class="notice"><%= flash[:notice] %></p>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/rodape' %>
    </div>
    <section>
      <%= debug(params) if Rails.env.development? %>
    </section>
  </body>
</html>

app/views/paginas/ajuda.html.erb
<% provide :title, "Ajuda" %>

<h1>Ajuda</h1>
<p>Para ajuda sobre Rails consulte o <a href="http://google.com">google</a>.</p>

app/views/paginas/index.html.erb
<% provide :title, "Início" %>

<h1>MicroBlog</h1>
<p>Está é uma aplicação exemplo pro módulo de Rails.</p>

<%= link_to "Crie sua conta!", signup_path, class: "signup_button round" %>

app/views/paginas/sobre.html.erb
<% provide :title, "Sobre" %>

<h1>Sobre</h1>
<p>O Curso de Rails da IT é um curso sobre Rails na IT.</p>

app/views/shared/_error_messages.html.erb
<% if @usuario.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      O formuário contém <%= pluralize(@usuario.errors.count, "erro") %>:
    </div>
    <ul>
    <% @usuario.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/usuarios/new.html.erb
<% provide(:title, "Cadastre-se") %>
<h1>Cadastre-se</h1>

<%= form_for(@usuario) do |f| %>
  <%= render 'shared/error_messages' %>

  <p>
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password, "Senha" %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation, "Confirme sua senha" %>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.submit "Criar minha conta" %>
  </p>
<% end %>

app/views/usuarios/show.html.erb
<% provide(:title, @usuario.nome) %>
<h1>
  <%= gravatar_for @usuario %>
  <%= @usuario.nome %>
</h1>